# Permission is hereby NOT granted beyond the terms of the individual
# exclusive license (see LICENSE); this file only configures the
# GitHub Sponsors button for the author's account.

github: [wild8highlander]
