#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Export frozen DTM tables to self-contained JS data files for the
chess-oracle web application.

The frozen artifacts results/dtm_krk.json.gz / dtm_kqk.json.gz are JSON
files (despite the .gz name) containing:
    stats        - the frozen certificate numbers of the retrograde build
    dtm_blob_b64 - base64 of a GZIP stream: 2^22 bytes, one per packed state
                   (wk | wq<<7 | bk<<14 | stm<<21), 0..63 = DTM in plies,
                   200 = drawn / illegal
    packing      - human-readable packing note
    bellman_verified - True (Bellman fixpoint over ALL states)

The web app must work offline from file:// (Termux), where fetch() is
blocked; therefore the payloads are wrapped as  <script>  globals:
    window.CHESS_ORACLE_DATA = { krk: {...}, kqk: {...},
                                 knk: {...}, kpk: {...} }
written to web/chess-oracle/assets/data/tables.js, plus a manifest with
SHA-256 checksums for the integrity panel.

Usage:  python3 scripts/export_web_tables.py
"""
import hashlib
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
RESULTS = os.path.join(ROOT, 'results')
OUT_DIR = os.path.join(ROOT, 'web', 'chess-oracle', 'assets', 'data')

SOURCES = {
    'krk': os.path.join(RESULTS, 'dtm_krk.json.gz'),
    'kqk': os.path.join(RESULTS, 'dtm_kqk.json.gz'),
    'knk': os.path.join(RESULTS, 'dtm_knk.json.gz'),
    'kpk': os.path.join(RESULTS, 'dtm_kpk.json.gz'),
}

FROZEN_STATS = {
    'krk': {'states': 399112, 'edges': 4447032, 'won': 376868,
            'mates': 216, 'max_plies': 32, 'max_moves': 16},
    'kqk': {'states': 368452, 'edges': 4869496, 'won': 345404,
            'mates': 364, 'max_plies': 20, 'max_moves': 10},
    # KNK: the negative control — a knight mate does not exist
    # (the lemma is re-proved by the integrity gate on every load)
    'knk': {'states': 429440, 'edges': 3521256, 'won': 0,
            'mates': 0, 'max_plies': 0, 'max_moves': 0},
    # KPK: promotion boundary = the frozen KQK certificate;
    # mates = 0 (every KPK mate is delivered after promotion, in KQK space)
    'kpk': {'states': 331352, 'edges': 2125630, 'won': 222558,
            'mates': 0, 'max_plies': 56, 'max_moves': 28},
}


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    payload = {}
    manifest = {'tables': {}}
    for kind, path in SOURCES.items():
        with open(path, 'r', encoding='utf-8') as f:
            data = json.load(f)
        # hard gate: the exported table must match the frozen certificate
        for k, v in FROZEN_STATS[kind].items():
            got = data['stats'].get(k)
            if got != v:
                sys.exit('FROZEN MISMATCH %s.%s: %r != %r'
                         % (kind, k, got, v))
        if not data.get('bellman_verified'):
            sys.exit('%s: bellman_verified is not True' % kind)
        raw = data['dtm_blob_b64'].encode('ascii')
        payload[kind] = {
            'piece': data['stats']['piece'],
            'stats': data['stats'],
            'packing': data['packing'],
            'bellman_verified': data['bellman_verified'],
            'blob': data['dtm_blob_b64'],
        }
        manifest['tables'][kind] = {
            'source': os.path.relpath(path, ROOT),
            'source_sha256': hashlib.sha256(
                open(path, 'rb').read()).hexdigest(),
            'stats': data['stats'],
        }
        print('%-4s <- %s (stats OK, bellman_verified=True)'
              % (kind, os.path.basename(path)))

    out_js = os.path.join(OUT_DIR, 'tables.js')
    with open(out_js, 'w', encoding='utf-8') as f:
        f.write('/* AUTO-GENERATED by scripts/export_web_tables.py — do not '
                'edit.\n   Frozen DTM certificates of chess-dynamics-lab '
                '(see results/). */\n')
        f.write('window.CHESS_ORACLE_DATA = ')
        json.dump(payload, f, separators=(',', ':'), ensure_ascii=True)
        f.write(';\n')
    manifest['export_sha256'] = hashlib.sha256(
        open(out_js, 'rb').read()).hexdigest()
    with open(os.path.join(OUT_DIR, 'manifest.json'), 'w',
              encoding='utf-8') as f:
        json.dump(manifest, f, indent=1)
    print('written: %s (%.1f KB)' % (os.path.relpath(out_js, ROOT),
                                     os.path.getsize(out_js) / 1024))
    print('written: manifest.json')
    return 0


if __name__ == '__main__':
    sys.exit(main())
